### ISSUE TITLE
ModuleNotFoundError for quantum_image_processing. 

### ISSUE THREAD

**Issue by siliconberry** [SaashaJoshi/quantum-image-processing#2]
Hi, When I tried to run mnist-frqi-representation.py or mnist-neqr-representation.py, I'm getting following error message. Can you pl take a look ? 

from quantum_image_processing.data_loader.mnist_data_loader import load_mnist_data
ModuleNotFoundError: No module named 'quantum_image_processing'

Thanks.

**Comment by SaashaJoshi** [comment]
Hey,
This is because a library needs to be installed on your personal computer before you can work with it. You can follow these steps to achieve that.

1. Clone this repository.
`git clone https://github.com/SaashaJoshi/quantum-image-processing.git`

2. Navigate to the repository
`cd path/quanutm_image_processing`

3. Install the library built in the repository
`pip install .`
